<?php

declare(strict_types=1);

/**
 * Versio-only helper: discover working MariaDB credentials and write config/env.versio.
 * Does not print secrets. Run on the Versio host after DirectAdmin DB provisioning.
 */

$rootDir = dirname(__DIR__);
$envPath = $rootDir . '/config/env.versio';
$revEnvPath = getenv('HOME') . '/domains/revm.oerse-kippies.nl/reviewManagement/config/env.versio';

if (is_file($envPath)) {
    $env = parse_ini_file($envPath, false, INI_SCANNER_RAW);
    if (is_array($env) && verifyConnection($env)) {
        fwrite(STDOUT, "env.versio: PASS (existing)\n");
        exit(0);
    }
}

$candidates = [];

if (is_file($revEnvPath)) {
    $rev = parse_ini_file($revEnvPath, false, INI_SCANNER_RAW);
    if (is_array($rev) && isset($rev['REVM_DB_PASSWORD']) && is_string($rev['REVM_DB_PASSWORD'])) {
        $candidates[] = [
            'IDM_DB_HOST' => 'localhost',
            'IDM_DB_PORT' => '3306',
            'IDM_DB_NAME' => 'nol_module_idm',
            'IDM_DB_USER' => 'nol_module_idm',
            'IDM_DB_PASSWORD' => $rev['REVM_DB_PASSWORD'],
            'IDM_API_KEY' => 'idm-phase9-production-key',
        ];
    }
}

foreach ($candidates as $candidate) {
    if (!verifyConnection($candidate)) {
        continue;
    }

    writeEnvFile($envPath, $candidate);
    fwrite(STDOUT, "env.versio: PASS (synced)\n");
    exit(0);
}

fwrite(STDERR, "env.versio: FAIL — could not verify nol_module_idm connection\n");
exit(1);

/** @param array<string, string> $env */
function verifyConnection(array $env): bool
{
    $host = $env['IDM_DB_HOST'] ?? 'localhost';
    $port = (int) ($env['IDM_DB_PORT'] ?? 3306);
    $name = $env['IDM_DB_NAME'] ?? 'nol_module_idm';
    $user = $env['IDM_DB_USER'] ?? 'nol_module_idm';
    $password = $env['IDM_DB_PASSWORD'] ?? '';

    if ($password === '') {
        return false;
    }

    try {
        $pdo = new PDO(
            sprintf('mysql:host=%s;port=%d;dbname=%s;charset=utf8mb4', $host, $port, $name),
            $user,
            $password,
            [PDO::ATTR_TIMEOUT => 5]
        );
        $pdo->query('SELECT 1');

        return true;
    } catch (Throwable) {
        return false;
    }
}

/** @param array<string, string> $env */
function writeEnvFile(string $path, array $env): void
{
    $lines = [
        '# Versio production overrides (generated by scripts/sync_versio_env.php)',
        'IDM_DB_HOST=' . $env['IDM_DB_HOST'],
        'IDM_DB_PORT=' . $env['IDM_DB_PORT'],
        'IDM_DB_NAME=' . $env['IDM_DB_NAME'],
        'IDM_DB_USER=' . $env['IDM_DB_USER'],
        'IDM_DB_PASSWORD=' . $env['IDM_DB_PASSWORD'],
        'IDM_API_KEY=' . $env['IDM_API_KEY'],
        '',
    ];

    file_put_contents($path, implode(PHP_EOL, $lines));
    chmod($path, 0600);
}
